spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/khana_khazana
    username: postgres
    password: mysecretpassword
  session:
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
